version: "3"

services:
  # MySQL
  dbserver:
    container_name: mysql_host
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: myapp
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    volumes:
      # 起動スクリプト
      - ./docker-compose/mysql/initdb:/docker-entrypoint-initdb.d
      # MySQLの設定ファイル
      - ./docker-compose/mysql/config:/etc/mysql/conf.d
      # DBの永続化
      - mysql_db:/var/lib/mysql
    ports:
    - 3306:3306

  # app
  app:
    container_name: spring_app
    build: ./docker-compose/spring
    depends_on:
      # dbserverが起動してからappを起動
      - dbserver
    ports:
      - "8080:8080"
    volumes:
      - .:/app
    environment:
      # mysqlの接続設定 host:portはコンテナ名指定
      spring.datasource.driverClassName: "com.mysql.cj.jdbc.Driver"
      spring.datasource.url: "jdbc:mysql://dbserver/test_database"
      spring.datasource.username: "root"
      spring.datasource.password: "root"

  # Redis
  redis:
    image: "redis:latest"
    ports:
      - "6379:6379"
    environment:
      TZ: Asia/Tokyo
    volumes:
      - "./data:/data"

# DBの永続化先
volumes:
  mysql_db:
    driver: local

